import { CalendarEventItem } from "./calendar-types";

export const INITIAL_CALENDAR_EVENTS: CalendarEventItem[] = [
  // Dec 30, 2024
  {
    id: "evt-dec30-1",
    title: "Monday standup",
    date: "2024-12-30",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
    description: "Weekly sync with development and creative teams.",
    participants: ["Sandy K.", "Anna Rossi", "Marcus Vance"],
    meetingLink: "https://meet.google.com/abc-loop-xyz",
  },
  {
    id: "evt-dec30-2",
    title: "Coffee with Alina",
    date: "2024-12-30",
    timeStart: "11:30 AM",
    timeEnd: "12:15 PM",
    theme: "purple",
    scope: "shared",
    project: "Client Relations",
    location: "Blue Bottle Coffee, 4th St",
    participants: ["Alina Vance", "Sandy K."],
  },
  {
    id: "evt-dec30-3",
    title: "Marketing site...",
    date: "2024-12-30",
    timeStart: "2:30 PM",
    timeEnd: "3:45 PM",
    theme: "blue",
    scope: "all",
    project: "Growth Initiative",
    description: "Review landing page animations and CTA metrics.",
  },
  {
    id: "evt-dec30-4",
    title: "Design System review",
    date: "2024-12-30",
    timeStart: "4:00 PM",
    timeEnd: "5:00 PM",
    theme: "blue",
    scope: "shared",
    project: "Design Ops",
  },
  {
    id: "evt-dec30-5",
    title: "End of year backlog triage",
    date: "2024-12-30",
    timeStart: "5:15 PM",
    timeEnd: "6:00 PM",
    theme: "neutral",
    scope: "all",
  },

  // Dec 31, 2024
  {
    id: "evt-dec31-1",
    title: "Monday standup",
    date: "2024-12-31",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
  },

  // Jan 2, 2025
  {
    id: "evt-jan2-1",
    title: "One-on-one wi...",
    date: "2025-01-02",
    timeStart: "10:00 AM",
    timeEnd: "10:45 AM",
    theme: "pink",
    scope: "shared",
    project: "Talent & Growth",
    description: "Quarterly alignment and career trajectory discussion.",
    participants: ["Sandy K.", "Amélie Laurent"],
  },
  {
    id: "evt-jan2-2",
    title: "All-hands meeti...",
    date: "2025-01-02",
    timeStart: "4:00 PM",
    timeEnd: "5:00 PM",
    theme: "neutral",
    scope: "public",
    project: "Company Wide",
    meetingLink: "https://meet.google.com/loop-all-hands",
  },
  {
    id: "evt-jan2-3",
    title: "Dinner with G...",
    date: "2025-01-02",
    timeStart: "6:30 PM",
    timeEnd: "8:30 PM",
    theme: "green",
    scope: "shared",
    hasBullet: true,
    location: "L’Osteria Downtown",
    participants: ["George C.", "Sandy K."],
  },

  // Jan 3, 2025
  {
    id: "evt-jan3-1",
    title: "Friday standup",
    date: "2025-01-03",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
  },

  // Jan 4, 2025
  {
    id: "evt-jan4-1",
    title: "House inspe...",
    date: "2025-01-04",
    timeStart: "10:30 AM",
    timeEnd: "12:00 PM",
    theme: "orange",
    scope: "public",
    hasBullet: true,
    location: "742 Evergreen Terrace",
  },

  // Jan 6, 2025
  {
    id: "evt-jan6-1",
    title: "Monday standup",
    date: "2025-01-06",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
  },
  {
    id: "evt-jan6-2",
    title: "Content planni...",
    date: "2025-01-06",
    timeStart: "11:00 AM",
    timeEnd: "12:15 PM",
    theme: "blue",
    scope: "shared",
    project: "Editorial & Content",
    description: "Q1 Social campaigns, case studies, and newsletter topics.",
  },

  // Jan 7, 2025
  {
    id: "evt-jan7-1",
    title: "One-on-one wi...",
    date: "2025-01-07",
    timeStart: "10:00 AM",
    timeEnd: "10:45 AM",
    theme: "pink",
    scope: "shared",
    project: "People Ops",
  },
  {
    id: "evt-jan7-2",
    title: "Catch up w/ Alex",
    date: "2025-01-07",
    timeStart: "2:30 PM",
    timeEnd: "3:15 PM",
    theme: "purple",
    scope: "all",
    project: "Creative Direction",
  },

  // Jan 8, 2025
  {
    id: "evt-jan8-1",
    title: "Deep work",
    date: "2025-01-08",
    timeStart: "9:00 AM",
    timeEnd: "10:30 AM",
    theme: "blue",
    scope: "all",
    project: "Focus Mode",
    description: "Focused UI refinement for agency client portal.",
  },
  {
    id: "evt-jan8-2",
    title: "Design sync",
    date: "2025-01-08",
    timeStart: "10:30 AM",
    timeEnd: "11:30 AM",
    theme: "blue",
    scope: "shared",
    project: "Design Studio",
  },
  {
    id: "evt-jan8-3",
    title: "SEO planning",
    date: "2025-01-08",
    timeStart: "1:30 PM",
    timeEnd: "2:30 PM",
    theme: "blue",
    scope: "public",
    project: "Marketing",
  },
  {
    id: "evt-jan8-4",
    title: "Sprint Retrospective",
    date: "2025-01-08",
    timeStart: "3:00 PM",
    timeEnd: "3:45 PM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan8-5",
    title: "Client contract review",
    date: "2025-01-08",
    timeStart: "4:00 PM",
    timeEnd: "4:45 PM",
    theme: "orange",
    scope: "shared",
  },
  {
    id: "evt-jan8-6",
    title: "Team social check-in",
    date: "2025-01-08",
    timeStart: "5:00 PM",
    timeEnd: "5:30 PM",
    theme: "pink",
    scope: "public",
  },

  // Jan 9, 2025
  {
    id: "evt-jan9-1",
    title: "Lunch with...",
    date: "2025-01-09",
    timeStart: "12:00 PM",
    timeEnd: "1:15 PM",
    theme: "green",
    scope: "shared",
    hasBullet: true,
    location: "Green Garden Bistro",
  },

  // Jan 10, 2025 (TODAY - HIGHLIGHTED)
  {
    id: "evt-jan10-1",
    title: "Friday standup",
    date: "2025-01-10",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
    meetingLink: "https://meet.google.com/loop-friday-sync",
  },
  {
    id: "evt-jan10-2",
    title: "Olivia x Riley",
    date: "2025-01-10",
    timeStart: "10:00 AM",
    timeEnd: "11:00 AM",
    theme: "purple",
    scope: "shared",
    project: "Brand Partnership",
    description: "Collaboration scope and deliverable timeline signoff.",
    participants: ["Olivia Hayes", "Riley Cooper", "Sandy K."],
  },
  {
    id: "evt-jan10-3",
    title: "Product demo",
    date: "2025-01-10",
    timeStart: "1:30 PM",
    timeEnd: "2:30 PM",
    theme: "blue",
    scope: "public",
    project: "V2 Release",
    description: "Demonstrating the new capacity dashboard to executive sponsors.",
    meetingLink: "https://meet.google.com/v2-live-demo",
  },

  // Jan 11, 2025
  {
    id: "evt-jan11-1",
    title: "House inspe...",
    date: "2025-01-11",
    timeStart: "11:00 AM",
    timeEnd: "12:30 PM",
    theme: "orange",
    scope: "all",
    hasBullet: true,
    location: "North Bay Residence",
  },

  // Jan 12, 2025
  {
    id: "evt-jan12-1",
    title: "Ava's engages...",
    date: "2025-01-12",
    timeStart: "1:00 PM",
    timeEnd: "4:00 PM",
    theme: "indigo",
    scope: "shared",
    hasBullet: true,
    location: "The Grand Pavilion",
  },

  // Jan 13, 2025
  {
    id: "evt-jan13-1",
    title: "Monday standup",
    date: "2025-01-13",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
  },
  {
    id: "evt-jan13-2",
    title: "Team lunch",
    date: "2025-01-13",
    timeStart: "12:15 PM",
    timeEnd: "1:30 PM",
    theme: "pink",
    scope: "shared",
    location: "Market Square Bistro",
  },

  // Jan 15, 2025
  {
    id: "evt-jan15-1",
    title: "Product planning",
    date: "2025-01-15",
    timeStart: "9:30 AM",
    timeEnd: "11:00 AM",
    theme: "blue",
    scope: "all",
    project: "Q2 Roadmap",
  },

  // Jan 16, 2025
  {
    id: "evt-jan16-1",
    title: "Amélie's first...",
    date: "2025-01-16",
    timeStart: "10:00 AM",
    timeEnd: "10:45 AM",
    theme: "pink",
    scope: "shared",
    project: "Onboarding",
  },
  {
    id: "evt-jan16-2",
    title: "All-hands meeti...",
    date: "2025-01-16",
    timeStart: "4:00 PM",
    timeEnd: "5:00 PM",
    theme: "neutral",
    scope: "public",
  },

  // Jan 17, 2025
  {
    id: "evt-jan17-1",
    title: "Friday standup",
    date: "2025-01-17",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan17-2",
    title: "Coffee w/ Amélie",
    date: "2025-01-17",
    timeStart: "9:30 AM",
    timeEnd: "10:15 AM",
    theme: "purple",
    scope: "shared",
  },
  {
    id: "evt-jan17-3",
    title: "Design feedbac...",
    date: "2025-01-17",
    timeStart: "2:30 PM",
    timeEnd: "3:30 PM",
    theme: "blue",
    scope: "all",
  },
  {
    id: "evt-jan17-4",
    title: "Weekly Release Audit",
    date: "2025-01-17",
    timeStart: "4:00 PM",
    timeEnd: "4:30 PM",
    theme: "neutral",
    scope: "all",
  },

  // Jan 18, 2025
  {
    id: "evt-jan18-1",
    title: "Half maratho...",
    date: "2025-01-18",
    timeStart: "7:00 AM",
    timeEnd: "10:30 AM",
    theme: "green",
    scope: "public",
    hasBullet: true,
    location: "Pacific Coast Highway",
  },

  // Jan 20, 2025
  {
    id: "evt-jan20-1",
    title: "Monday standup",
    date: "2025-01-20",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan20-2",
    title: "Deep work",
    date: "2025-01-20",
    timeStart: "9:15 AM",
    timeEnd: "11:30 AM",
    theme: "blue",
    scope: "all",
  },

  // Jan 21, 2025
  {
    id: "evt-jan21-1",
    title: "Quarterly review",
    date: "2025-01-21",
    timeStart: "11:30 AM",
    timeEnd: "12:30 PM",
    theme: "orange",
    scope: "public",
    project: "Financials",
  },
  {
    id: "evt-jan21-2",
    title: "Lunch with Zahir",
    date: "2025-01-21",
    timeStart: "1:00 PM",
    timeEnd: "2:15 PM",
    theme: "purple",
    scope: "shared",
  },
  {
    id: "evt-jan21-3",
    title: "Dinner with C...",
    date: "2025-01-21",
    timeStart: "7:00 PM",
    timeEnd: "9:00 PM",
    theme: "green",
    scope: "shared",
    hasBullet: true,
  },

  // Jan 22, 2025
  {
    id: "evt-jan22-1",
    title: "Deep work",
    date: "2025-01-22",
    timeStart: "9:00 AM",
    timeEnd: "11:00 AM",
    theme: "blue",
    scope: "all",
  },
  {
    id: "evt-jan22-2",
    title: "Design sync",
    date: "2025-01-22",
    timeStart: "2:30 PM",
    timeEnd: "3:30 PM",
    theme: "blue",
    scope: "shared",
  },

  // Jan 23, 2025
  {
    id: "evt-jan23-1",
    title: "Amélie coffee",
    date: "2025-01-23",
    timeStart: "10:00 AM",
    timeEnd: "10:45 AM",
    theme: "pink",
    scope: "shared",
  },

  // Jan 24, 2025
  {
    id: "evt-jan24-1",
    title: "Friday standup",
    date: "2025-01-24",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan24-2",
    title: "Accountant",
    date: "2025-01-24",
    timeStart: "1:45 PM",
    timeEnd: "2:30 PM",
    theme: "yellow",
    scope: "public",
    project: "Finance & Tax",
  },
  {
    id: "evt-jan24-3",
    title: "Marketing site...",
    date: "2025-01-24",
    timeStart: "2:30 PM",
    timeEnd: "3:30 PM",
    theme: "blue",
    scope: "all",
  },
  {
    id: "evt-jan24-4",
    title: "Agency Pod wrapup",
    date: "2025-01-24",
    timeStart: "4:00 PM",
    timeEnd: "4:45 PM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan24-5",
    title: "Capacity forecasting",
    date: "2025-01-24",
    timeStart: "5:00 PM",
    timeEnd: "5:30 PM",
    theme: "blue",
    scope: "shared",
  },
  {
    id: "evt-jan24-6",
    title: "Team cheers",
    date: "2025-01-24",
    timeStart: "5:45 PM",
    timeEnd: "6:45 PM",
    theme: "pink",
    scope: "public",
  },

  // Jan 27, 2025
  {
    id: "evt-jan27-1",
    title: "Monday standup",
    date: "2025-01-27",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },

  // Jan 28, 2025
  {
    id: "evt-jan28-1",
    title: "Content planni...",
    date: "2025-01-28",
    timeStart: "11:00 AM",
    timeEnd: "12:00 PM",
    theme: "blue",
    scope: "shared",
  },
  {
    id: "evt-jan28-2",
    title: "Lunch with Alina",
    date: "2025-01-28",
    timeStart: "12:45 PM",
    timeEnd: "1:45 PM",
    theme: "purple",
    scope: "shared",
  },

  // Jan 29, 2025
  {
    id: "evt-jan29-1",
    title: "Product planning",
    date: "2025-01-29",
    timeStart: "9:30 AM",
    timeEnd: "10:30 AM",
    theme: "blue",
    scope: "all",
  },

  // Jan 30, 2025
  {
    id: "evt-jan30-1",
    title: "All-hands meeti...",
    date: "2025-01-30",
    timeStart: "4:00 PM",
    timeEnd: "5:00 PM",
    theme: "neutral",
    scope: "public",
  },
  {
    id: "evt-jan30-2",
    title: "Team dinner",
    date: "2025-01-30",
    timeStart: "5:30 PM",
    timeEnd: "8:00 PM",
    theme: "pink",
    scope: "shared",
    location: "Trattoria Della Nonna",
  },

  // Jan 31, 2025
  {
    id: "evt-jan31-1",
    title: "Friday standup",
    date: "2025-01-31",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },

  // Feb 2, 2025
  {
    id: "evt-feb2-1",
    title: "Monday standup",
    date: "2025-02-02",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
];
