import { CalendarEventItem } from "./calendar-types";

export const INITIAL_CALENDAR_EVENTS: CalendarEventItem[] = [
  // === SEPTEMBER 2026 (Live Current Month) ===
  // Sep 1, 2026 (Tuesday)
  {
    id: "evt-sep1-1",
    title: "Q3 Sprint Kickoff",
    date: "2026-09-01",
    timeStart: "9:00 AM",
    timeEnd: "10:00 AM",
    theme: "neutral",
    scope: "all",
    project: "Studio Operations",
    description: "Setting cross-functional priorities and deliverable targets for September.",
  },
  {
    id: "evt-sep1-2",
    title: "Brand identity sync",
    date: "2026-09-01",
    timeStart: "2:00 PM",
    timeEnd: "3:00 PM",
    theme: "purple",
    scope: "shared",
    project: "Northwind",
    participants: ["Sara D.", "Sandy K."],
  },

  // Sep 2, 2026 (Wednesday)
  {
    id: "evt-sep2-1",
    title: "Motion boards v3",
    date: "2026-09-02",
    timeStart: "10:30 AM",
    timeEnd: "11:30 AM",
    theme: "blue",
    scope: "shared",
    project: "Kite Motors",
  },
  {
    id: "evt-sep2-2",
    title: "Design token review",
    date: "2026-09-02",
    timeStart: "3:00 PM",
    timeEnd: "4:00 PM",
    theme: "pink",
    scope: "all",
    project: "Design System",
  },

  // Sep 3, 2026 (Thursday)
  {
    id: "evt-sep3-1",
    title: "Client status call",
    date: "2026-09-03",
    timeStart: "11:00 AM",
    timeEnd: "11:45 AM",
    theme: "orange",
    scope: "shared",
    project: "Meridian",
    location: "Google Meet",
  },

  // Sep 4, 2026 (Friday)
  {
    id: "evt-sep4-1",
    title: "Friday standup",
    date: "2026-09-04",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Studio Ops",
  },
  {
    id: "evt-sep4-2",
    title: "Demo & Drinks",
    date: "2026-09-04",
    timeStart: "4:30 PM",
    timeEnd: "6:00 PM",
    theme: "pink",
    scope: "public",
    location: "Studio Courtyard",
  },

  // Sep 7, 2026 (Monday)
  {
    id: "evt-sep7-1",
    title: "Monday standup",
    date: "2026-09-07",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-sep7-2",
    title: "Product film cut",
    date: "2026-09-07",
    timeStart: "1:30 PM",
    timeEnd: "2:45 PM",
    theme: "blue",
    scope: "shared",
    project: "Kite Motors",
  },

  // Sep 8, 2026 (Tuesday)
  {
    id: "evt-sep8-1",
    title: "Design Critique",
    date: "2026-09-08",
    timeStart: "10:00 AM",
    timeEnd: "11:00 AM",
    theme: "purple",
    scope: "shared",
    project: "Mobile App",
  },

  // Sep 9, 2026 (Wednesday)
  {
    id: "evt-sep9-1",
    title: "Meridian presentation",
    date: "2026-09-09",
    timeStart: "2:00 PM",
    timeEnd: "3:30 PM",
    theme: "orange",
    scope: "shared",
    hasBullet: true,
    project: "Meridian Print",
  },

  // Sep 10, 2026 (Thursday)
  {
    id: "evt-sep10-1",
    title: "Sprint check-in",
    date: "2026-09-10",
    timeStart: "11:00 AM",
    timeEnd: "11:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-sep10-2",
    title: "1-on-1 with Clara",
    date: "2026-09-10",
    timeStart: "3:00 PM",
    timeEnd: "3:45 PM",
    theme: "pink",
    scope: "shared",
  },

  // Sep 11, 2026 (Friday)
  {
    id: "evt-sep11-1",
    title: "Friday standup",
    date: "2026-09-11",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-sep11-2",
    title: "Release candidate v2.4",
    date: "2026-09-11",
    timeStart: "2:00 PM",
    timeEnd: "3:30 PM",
    theme: "blue",
    scope: "public",
  },

  // Sep 14, 2026 (Monday)
  {
    id: "evt-sep14-1",
    title: "Monday standup",
    date: "2026-09-14",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-sep14-2",
    title: "Helix Health landing copy",
    date: "2026-09-14",
    timeStart: "11:30 AM",
    timeEnd: "12:30 PM",
    theme: "green",
    scope: "shared",
  },

  // Sep 15, 2026 (Tuesday)
  {
    id: "evt-sep15-1",
    title: "Design System sync",
    date: "2026-09-15",
    timeStart: "10:00 AM",
    timeEnd: "11:00 AM",
    theme: "purple",
    scope: "shared",
  },
  {
    id: "evt-sep15-2",
    title: "Security audit",
    date: "2026-09-15",
    timeStart: "3:00 PM",
    timeEnd: "4:00 PM",
    theme: "neutral",
    scope: "all",
  },

  // Sep 16, 2026 (Wednesday)
  {
    id: "evt-sep16-1",
    title: "Northwind hero direction",
    date: "2026-09-16",
    timeStart: "11:00 AM",
    timeEnd: "12:15 PM",
    theme: "blue",
    scope: "shared",
  },
  {
    id: "evt-sep16-2",
    title: "Coffee with Alina",
    date: "2026-09-16",
    timeStart: "2:30 PM",
    timeEnd: "3:15 PM",
    theme: "pink",
    scope: "shared",
    location: "Blue Bottle Coffee",
  },

  // Sep 17, 2026 (Thursday - TODAY)
  {
    id: "evt-sep17-1",
    title: "Daily team standup",
    date: "2026-09-17",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
    meetingLink: "https://meet.google.com/loop-daily-sync",
    participants: ["Sandy K.", "Marcus Vance", "Anna Rossi"],
  },
  {
    id: "evt-sep17-2",
    title: "Olivia x Riley — Q3 Sync",
    date: "2026-09-17",
    timeStart: "10:00 AM",
    timeEnd: "11:00 AM",
    theme: "purple",
    scope: "shared",
    project: "Brand Partnership",
    description: "Collaboration scope and deliverable timeline signoff.",
    participants: ["Olivia Hayes", "Riley Cooper", "Sandy K."],
  },
  {
    id: "evt-sep17-3",
    title: "Product demo & QA",
    date: "2026-09-17",
    timeStart: "1:30 PM",
    timeEnd: "2:30 PM",
    theme: "blue",
    scope: "public",
    project: "V2 Release",
    description: "Demonstrating the new capacity dashboard to executive sponsors.",
    meetingLink: "https://meet.google.com/v2-live-demo",
  },
  {
    id: "evt-sep17-4",
    title: "Design Critique & Tokens",
    date: "2026-09-17",
    timeStart: "3:30 PM",
    timeEnd: "4:30 PM",
    theme: "pink",
    scope: "shared",
    project: "Design Ops",
    description: "Typography hierarchy and color tokens audit for dark mode.",
  },
  {
    id: "evt-sep17-5",
    title: "Sprint wrap-up",
    date: "2026-09-17",
    timeStart: "5:00 PM",
    timeEnd: "5:45 PM",
    theme: "orange",
    scope: "all",
    hasBullet: true,
  },

  // Sep 18, 2026 (Friday)
  {
    id: "evt-sep18-1",
    title: "Friday standup",
    date: "2026-09-18",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-sep18-2",
    title: "Design system review",
    date: "2026-09-18",
    timeStart: "1:30 PM",
    timeEnd: "2:45 PM",
    theme: "blue",
    scope: "shared",
  },
  {
    id: "evt-sep18-3",
    title: "Studio happy hour",
    date: "2026-09-18",
    timeStart: "5:00 PM",
    timeEnd: "7:00 PM",
    theme: "pink",
    scope: "public",
  },

  // Sep 21, 2026 (Monday)
  {
    id: "evt-sep21-1",
    title: "Monday standup",
    date: "2026-09-21",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-sep21-2",
    title: "Client onboarding — Apex",
    date: "2026-09-21",
    timeStart: "2:00 PM",
    timeEnd: "3:15 PM",
    theme: "purple",
    scope: "shared",
  },

  // Sep 22, 2026 (Tuesday)
  {
    id: "evt-sep22-1",
    title: "Prototype testing",
    date: "2026-09-22",
    timeStart: "10:30 AM",
    timeEnd: "11:45 AM",
    theme: "blue",
    scope: "shared",
  },

  // Sep 23, 2026 (Wednesday)
  {
    id: "evt-sep23-1",
    title: "Motion reel review",
    date: "2026-09-23",
    timeStart: "1:30 PM",
    timeEnd: "2:30 PM",
    theme: "orange",
    scope: "all",
  },

  // Sep 24, 2026 (Thursday)
  {
    id: "evt-sep24-1",
    title: "All-hands meeting",
    date: "2026-09-24",
    timeStart: "4:00 PM",
    timeEnd: "5:00 PM",
    theme: "neutral",
    scope: "public",
    meetingLink: "https://meet.google.com/loop-all-hands",
  },

  // Sep 25, 2026 (Friday)
  {
    id: "evt-sep25-1",
    title: "Friday standup",
    date: "2026-09-25",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-sep25-2",
    title: "Team lunch",
    date: "2026-09-25",
    timeStart: "12:30 PM",
    timeEnd: "2:00 PM",
    theme: "pink",
    scope: "public",
  },

  // Sep 28, 2026 (Monday)
  {
    id: "evt-sep28-1",
    title: "Monday standup",
    date: "2026-09-28",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },

  // Sep 29, 2026 (Tuesday)
  {
    id: "evt-sep29-1",
    title: "Q4 Planning session",
    date: "2026-09-29",
    timeStart: "2:00 PM",
    timeEnd: "4:00 PM",
    theme: "purple",
    scope: "shared",
  },

  // Sep 30, 2026 (Wednesday)
  {
    id: "evt-sep30-1",
    title: "End of month retro",
    date: "2026-09-30",
    timeStart: "4:00 PM",
    timeEnd: "5:30 PM",
    theme: "blue",
    scope: "all",
  },

  // === HISTORIC EVENTS (Dec 2024 / Jan 2025) ===
  {
    id: "evt-dec30-1",
    title: "Monday standup",
    date: "2024-12-30",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
    description: "Weekly sync with development and creative teams.",
    participants: ["Sandy K.", "Anna Rossi", "Marcus Vance"],
    meetingLink: "https://meet.google.com/abc-loop-xyz",
  },
  {
    id: "evt-dec30-2",
    title: "Coffee with Alina",
    date: "2024-12-30",
    timeStart: "11:30 AM",
    timeEnd: "12:15 PM",
    theme: "purple",
    scope: "shared",
    project: "Client Relations",
    location: "Blue Bottle Coffee, 4th St",
    participants: ["Alina Vance", "Sandy K."],
  },
  {
    id: "evt-dec30-3",
    title: "Marketing site...",
    date: "2024-12-30",
    timeStart: "2:30 PM",
    timeEnd: "3:45 PM",
    theme: "blue",
    scope: "all",
    project: "Growth Initiative",
    description: "Review landing page animations and CTA metrics.",
  },
  {
    id: "evt-dec30-4",
    title: "Design System review",
    date: "2024-12-30",
    timeStart: "4:00 PM",
    timeEnd: "5:00 PM",
    theme: "blue",
    scope: "shared",
    project: "Design Ops",
  },
  {
    id: "evt-dec30-5",
    title: "End of year backlog triage",
    date: "2024-12-30",
    timeStart: "5:15 PM",
    timeEnd: "6:00 PM",
    theme: "neutral",
    scope: "all",
  },

  // Dec 31, 2024
  {
    id: "evt-dec31-1",
    title: "Monday standup",
    date: "2024-12-31",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
  },

  // Jan 2, 2025
  {
    id: "evt-jan2-1",
    title: "One-on-one wi...",
    date: "2025-01-02",
    timeStart: "10:00 AM",
    timeEnd: "10:45 AM",
    theme: "pink",
    scope: "shared",
    project: "Talent & Growth",
    description: "Quarterly alignment and career trajectory discussion.",
    participants: ["Sandy K.", "Amélie Laurent"],
  },
  {
    id: "evt-jan2-2",
    title: "All-hands meeti...",
    date: "2025-01-02",
    timeStart: "4:00 PM",
    timeEnd: "5:00 PM",
    theme: "neutral",
    scope: "public",
    project: "Company Wide",
    meetingLink: "https://meet.google.com/loop-all-hands",
  },
  {
    id: "evt-jan2-3",
    title: "Dinner with G...",
    date: "2025-01-02",
    timeStart: "6:30 PM",
    timeEnd: "8:30 PM",
    theme: "green",
    scope: "shared",
    hasBullet: true,
    location: "L’Osteria Downtown",
    participants: ["George C.", "Sandy K."],
  },

  // Jan 3, 2025
  {
    id: "evt-jan3-1",
    title: "Friday standup",
    date: "2025-01-03",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
  },

  // Jan 4, 2025
  {
    id: "evt-jan4-1",
    title: "House inspe...",
    date: "2025-01-04",
    timeStart: "10:30 AM",
    timeEnd: "12:00 PM",
    theme: "orange",
    scope: "public",
    hasBullet: true,
    location: "742 Evergreen Terrace",
  },

  // Jan 6, 2025
  {
    id: "evt-jan6-1",
    title: "Monday standup",
    date: "2025-01-06",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
  },
  {
    id: "evt-jan6-2",
    title: "Content planni...",
    date: "2025-01-06",
    timeStart: "11:00 AM",
    timeEnd: "12:15 PM",
    theme: "blue",
    scope: "shared",
    project: "Editorial & Content",
    description: "Q1 Social campaigns, case studies, and newsletter topics.",
  },

  // Jan 7, 2025
  {
    id: "evt-jan7-1",
    title: "One-on-one wi...",
    date: "2025-01-07",
    timeStart: "10:00 AM",
    timeEnd: "10:45 AM",
    theme: "pink",
    scope: "shared",
    project: "People Ops",
  },
  {
    id: "evt-jan7-2",
    title: "Catch up w/ Alex",
    date: "2025-01-07",
    timeStart: "2:30 PM",
    timeEnd: "3:15 PM",
    theme: "purple",
    scope: "all",
    project: "Creative Direction",
  },

  // Jan 8, 2025
  {
    id: "evt-jan8-1",
    title: "Deep work",
    date: "2025-01-08",
    timeStart: "9:00 AM",
    timeEnd: "10:30 AM",
    theme: "blue",
    scope: "all",
    project: "Focus Mode",
    description: "Focused UI refinement for agency client portal.",
  },
  {
    id: "evt-jan8-2",
    title: "Design sync",
    date: "2025-01-08",
    timeStart: "10:30 AM",
    timeEnd: "11:30 AM",
    theme: "blue",
    scope: "shared",
    project: "Design Studio",
  },
  {
    id: "evt-jan8-3",
    title: "SEO planning",
    date: "2025-01-08",
    timeStart: "1:30 PM",
    timeEnd: "2:30 PM",
    theme: "blue",
    scope: "public",
    project: "Marketing",
  },
  {
    id: "evt-jan8-4",
    title: "Sprint Retrospective",
    date: "2025-01-08",
    timeStart: "3:00 PM",
    timeEnd: "3:45 PM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan8-5",
    title: "Client contract review",
    date: "2025-01-08",
    timeStart: "4:00 PM",
    timeEnd: "4:45 PM",
    theme: "orange",
    scope: "shared",
  },
  {
    id: "evt-jan8-6",
    title: "Team social check-in",
    date: "2025-01-08",
    timeStart: "5:00 PM",
    timeEnd: "5:30 PM",
    theme: "pink",
    scope: "public",
  },

  // Jan 9, 2025
  {
    id: "evt-jan9-1",
    title: "Lunch with...",
    date: "2025-01-09",
    timeStart: "12:00 PM",
    timeEnd: "1:15 PM",
    theme: "green",
    scope: "shared",
    hasBullet: true,
    location: "Green Garden Bistro",
  },

  // Jan 10, 2025 (TODAY - HIGHLIGHTED)
  {
    id: "evt-jan10-1",
    title: "Friday standup",
    date: "2025-01-10",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
    meetingLink: "https://meet.google.com/loop-friday-sync",
  },
  {
    id: "evt-jan10-2",
    title: "Olivia x Riley",
    date: "2025-01-10",
    timeStart: "10:00 AM",
    timeEnd: "11:00 AM",
    theme: "purple",
    scope: "shared",
    project: "Brand Partnership",
    description: "Collaboration scope and deliverable timeline signoff.",
    participants: ["Olivia Hayes", "Riley Cooper", "Sandy K."],
  },
  {
    id: "evt-jan10-3",
    title: "Product demo",
    date: "2025-01-10",
    timeStart: "1:30 PM",
    timeEnd: "2:30 PM",
    theme: "blue",
    scope: "public",
    project: "V2 Release",
    description: "Demonstrating the new capacity dashboard to executive sponsors.",
    meetingLink: "https://meet.google.com/v2-live-demo",
  },

  // Jan 11, 2025
  {
    id: "evt-jan11-1",
    title: "House inspe...",
    date: "2025-01-11",
    timeStart: "11:00 AM",
    timeEnd: "12:30 PM",
    theme: "orange",
    scope: "all",
    hasBullet: true,
    location: "North Bay Residence",
  },

  // Jan 12, 2025
  {
    id: "evt-jan12-1",
    title: "Ava's engages...",
    date: "2025-01-12",
    timeStart: "1:00 PM",
    timeEnd: "4:00 PM",
    theme: "indigo",
    scope: "shared",
    hasBullet: true,
    location: "The Grand Pavilion",
  },

  // Jan 13, 2025
  {
    id: "evt-jan13-1",
    title: "Monday standup",
    date: "2025-01-13",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
    project: "Internal Ops",
  },
  {
    id: "evt-jan13-2",
    title: "Team lunch",
    date: "2025-01-13",
    timeStart: "12:15 PM",
    timeEnd: "1:30 PM",
    theme: "pink",
    scope: "shared",
    location: "Market Square Bistro",
  },

  // Jan 15, 2025
  {
    id: "evt-jan15-1",
    title: "Product planning",
    date: "2025-01-15",
    timeStart: "9:30 AM",
    timeEnd: "11:00 AM",
    theme: "blue",
    scope: "all",
    project: "Q2 Roadmap",
  },

  // Jan 16, 2025
  {
    id: "evt-jan16-1",
    title: "Amélie's first...",
    date: "2025-01-16",
    timeStart: "10:00 AM",
    timeEnd: "10:45 AM",
    theme: "pink",
    scope: "shared",
    project: "Onboarding",
  },
  {
    id: "evt-jan16-2",
    title: "All-hands meeti...",
    date: "2025-01-16",
    timeStart: "4:00 PM",
    timeEnd: "5:00 PM",
    theme: "neutral",
    scope: "public",
  },

  // Jan 17, 2025
  {
    id: "evt-jan17-1",
    title: "Friday standup",
    date: "2025-01-17",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan17-2",
    title: "Coffee w/ Amélie",
    date: "2025-01-17",
    timeStart: "9:30 AM",
    timeEnd: "10:15 AM",
    theme: "purple",
    scope: "shared",
  },
  {
    id: "evt-jan17-3",
    title: "Design feedbac...",
    date: "2025-01-17",
    timeStart: "2:30 PM",
    timeEnd: "3:30 PM",
    theme: "blue",
    scope: "all",
  },
  {
    id: "evt-jan17-4",
    title: "Weekly Release Audit",
    date: "2025-01-17",
    timeStart: "4:00 PM",
    timeEnd: "4:30 PM",
    theme: "neutral",
    scope: "all",
  },

  // Jan 18, 2025
  {
    id: "evt-jan18-1",
    title: "Half maratho...",
    date: "2025-01-18",
    timeStart: "7:00 AM",
    timeEnd: "10:30 AM",
    theme: "green",
    scope: "public",
    hasBullet: true,
    location: "Pacific Coast Highway",
  },

  // Jan 20, 2025
  {
    id: "evt-jan20-1",
    title: "Monday standup",
    date: "2025-01-20",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan20-2",
    title: "Deep work",
    date: "2025-01-20",
    timeStart: "9:15 AM",
    timeEnd: "11:30 AM",
    theme: "blue",
    scope: "all",
  },

  // Jan 21, 2025
  {
    id: "evt-jan21-1",
    title: "Quarterly review",
    date: "2025-01-21",
    timeStart: "11:30 AM",
    timeEnd: "12:30 PM",
    theme: "orange",
    scope: "public",
    project: "Financials",
  },
  {
    id: "evt-jan21-2",
    title: "Lunch with Zahir",
    date: "2025-01-21",
    timeStart: "1:00 PM",
    timeEnd: "2:15 PM",
    theme: "purple",
    scope: "shared",
  },
  {
    id: "evt-jan21-3",
    title: "Dinner with C...",
    date: "2025-01-21",
    timeStart: "7:00 PM",
    timeEnd: "9:00 PM",
    theme: "green",
    scope: "shared",
    hasBullet: true,
  },

  // Jan 22, 2025
  {
    id: "evt-jan22-1",
    title: "Deep work",
    date: "2025-01-22",
    timeStart: "9:00 AM",
    timeEnd: "11:00 AM",
    theme: "blue",
    scope: "all",
  },
  {
    id: "evt-jan22-2",
    title: "Design sync",
    date: "2025-01-22",
    timeStart: "2:30 PM",
    timeEnd: "3:30 PM",
    theme: "blue",
    scope: "shared",
  },

  // Jan 23, 2025
  {
    id: "evt-jan23-1",
    title: "Amélie coffee",
    date: "2025-01-23",
    timeStart: "10:00 AM",
    timeEnd: "10:45 AM",
    theme: "pink",
    scope: "shared",
  },

  // Jan 24, 2025
  {
    id: "evt-jan24-1",
    title: "Friday standup",
    date: "2025-01-24",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan24-2",
    title: "Accountant",
    date: "2025-01-24",
    timeStart: "1:45 PM",
    timeEnd: "2:30 PM",
    theme: "yellow",
    scope: "public",
    project: "Finance & Tax",
  },
  {
    id: "evt-jan24-3",
    title: "Marketing site...",
    date: "2025-01-24",
    timeStart: "2:30 PM",
    timeEnd: "3:30 PM",
    theme: "blue",
    scope: "all",
  },
  {
    id: "evt-jan24-4",
    title: "Agency Pod wrapup",
    date: "2025-01-24",
    timeStart: "4:00 PM",
    timeEnd: "4:45 PM",
    theme: "neutral",
    scope: "all",
  },
  {
    id: "evt-jan24-5",
    title: "Capacity forecasting",
    date: "2025-01-24",
    timeStart: "5:00 PM",
    timeEnd: "5:30 PM",
    theme: "blue",
    scope: "shared",
  },
  {
    id: "evt-jan24-6",
    title: "Team cheers",
    date: "2025-01-24",
    timeStart: "5:45 PM",
    timeEnd: "6:45 PM",
    theme: "pink",
    scope: "public",
  },

  // Jan 27, 2025
  {
    id: "evt-jan27-1",
    title: "Monday standup",
    date: "2025-01-27",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },

  // Jan 28, 2025
  {
    id: "evt-jan28-1",
    title: "Content planni...",
    date: "2025-01-28",
    timeStart: "11:00 AM",
    timeEnd: "12:00 PM",
    theme: "blue",
    scope: "shared",
  },
  {
    id: "evt-jan28-2",
    title: "Lunch with Alina",
    date: "2025-01-28",
    timeStart: "12:45 PM",
    timeEnd: "1:45 PM",
    theme: "purple",
    scope: "shared",
  },

  // Jan 29, 2025
  {
    id: "evt-jan29-1",
    title: "Product planning",
    date: "2025-01-29",
    timeStart: "9:30 AM",
    timeEnd: "10:30 AM",
    theme: "blue",
    scope: "all",
  },

  // Jan 30, 2025
  {
    id: "evt-jan30-1",
    title: "All-hands meeti...",
    date: "2025-01-30",
    timeStart: "4:00 PM",
    timeEnd: "5:00 PM",
    theme: "neutral",
    scope: "public",
  },
  {
    id: "evt-jan30-2",
    title: "Team dinner",
    date: "2025-01-30",
    timeStart: "5:30 PM",
    timeEnd: "8:00 PM",
    theme: "pink",
    scope: "shared",
    location: "Trattoria Della Nonna",
  },

  // Jan 31, 2025
  {
    id: "evt-jan31-1",
    title: "Friday standup",
    date: "2025-01-31",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },

  // Feb 2, 2025
  {
    id: "evt-feb2-1",
    title: "Monday standup",
    date: "2025-02-02",
    timeStart: "9:00 AM",
    timeEnd: "9:30 AM",
    theme: "neutral",
    scope: "all",
  },
];
