/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/clients': typeof ClientsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/clients': typeof ClientsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/clients': typeof ClientsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/clients'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/clients'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/clients'
    | '/messages'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  ClientsRoute: typeof ClientsRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  ClientsRoute: ClientsRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
